### ISSUE TITLE
Wrong logic: This logic allows your team to get a portion of the cost

### ISSUE THREAD

**Issue by huwentao1** [aave/protocol-v2#22] opened 2021-02-04 08:17 UTC
this is incorrect logic code
![image](https://user-images.githubusercontent.com/43719888/106863770-f2bd7f00-6703-11eb-82f3-a4602c56e68f.png)
I think if no one borrows through **stableRate** for a long time, then stableSupplyUpdatedTimestamp will **not be updated,** but **timestamp** is always updated. Therefore, the value of  ``` timestamp-stableSupplyUpdatedTimestamp ```
will become **larger and larger.** Fee, it’s wrong.

**Comment by Zer0dot** [comment] 2021-02-06 22:27
I may not be 100% the best person to answer this- but it seems like it works as intended. Right below your highlight you can see that this is actually used to multiply the stable debt principal balance- resulting in the total debt at time ``timestamp,`` which is the previous reserve update.

This is then *subtracted* from the total debt at this current timestamp. So this works regardless of the last stable supply update, since  ``vars.currentStableDebt`` is obtained from ``_calcTotalSupply`` which uses the current timestamp on a stable debt token and ``vars.previousStableDebt`` is obtained from essentially the same calculation, but with the last reserve update timestamp instead of the current timestamp. Both use the same stable supply update timestamp.

At least that's how I would explain it.

**Comment by ernesto-usal** [comment] 2021-02-07 10:16
+1 on the previous answer by @Zer0dot .
In simple terms, we need to use the current timestamp and the one of the previous update on the stable debt token if we want to calculate how much interest has been accrued in time, compounded.

**Comment by ernesto-usal** [comment] 2021-02-18 08:46
Closing it, not being an issue

**Closed by ernesto-usal** 2021-02-18 08:46 UTC
